### ISSUE TITLE
Fix mobile nav open and collapsed states

### ISSUE THREAD

**Issue by julianbolts** [julianfresco/broen#14]
There are some issues with the mobile nav:
- `mobileOpen` state seems to be opposite of displayed state (css seems to agree too)
- in some places, the mobile-collapsed look takes up some white space

Suggested fix (broen.css):

``` css

/* Mobile look */
@media (max-width: 767px) {
  .broen-nav-container {
    position: static;
    height: auto;
    width: auto;
    transition: opacity .2s, max-height .2s, z-index .2s;
    opacity: 0;
    max-height: 0;
    opacity: 1;
    max-height: 1200px;
    z-index: auto;
  }

  .broen-nav-container.nav-mobile-collapsed {
    opacity: 0;
    max-height: 0;
    z-index: -1;
  }

  .broen-navbar.navbar-mobile-open,
  .navbar-mobile-open .broen-nav,
  .navbar-mobile-open .broen-nav-item,
  .navbar-mobile-open .nav-item-container {
    max-height: initial;
    display: block;
  }

  .broen-navbar,
  .broen-nav,
  .broen-nav-item,
  .nav-item-container {
    max-height: 0;
    display: none;
  }

  #toggle-expand,
  #toggle-compress {
    display: none;
  }

  .broen-navbar {
    border-top: none;
  }
}
```
