### ISSUE TITLE
Unable to scroll on very long views

### ISSUE THREAD

**Issue by julianbolts** [julianfresco/broen#16]
Observed in a view with very long height (renders height >15,000px), the `.broen-page` can observe an unusually large height and lose the scrollbar (tested on Chrome on Mac OSX)

Suggestion:
In `src/styles/_broen.scss`, add 100% value to all 3 height limits:

``` css
.broen-page {
  min-height: 100%;
  max-height: 100%;
  height: 100%;
}
```

**Comment by julianbolts** [comment]
It was discovered that the need for setting the `height` and `max-height` was only applicable in an app that had set the following:

In yourApp.css:

``` css
.broen-page {
    overflow: auto;
}
```

Thus, not fixing unless there is a future need.

BTW, the application using the above setting was an attempt to fix issue #17 Fixed size block elements scroll off page
